name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push udagram-reverseproxy aklile/udagram-reverseproxy:v3a
    - run: docker push udagram-api-feed aklile/udagram-api-feed:v4a
    - run: docker push udagram-api-user aklile/udagram-api-user:v4a
    - run: docker push udagram-frontend aklile/udagram-frontend:local
