name: Node.js CI

on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      # - run: docker-compose -f docker-compose-build.yaml build --parallel
      - run: docker --version # print the version for logging
      - run: docker build -t udagram-reverseproxy ./udagram-reverseproxy
      - run: docker build -t udagram-api-feed ./udagram-api-feed
      - run: docker build -t udagram-api-user ./udagram-api-user
      - run: docker build -t udagram-frontend ./udagram-frontend
      - run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
      - run: docker tag udagram-reverseproxy aklile/udagram-reverseproxy:v4a
      - run: docker tag udagram-api-feed aklile/udagram-api-feed:v4a
      - run: docker tag udagram-api-user aklile/udagram-api-user:v4a
      - run: docker tag udagram-frontend aklile/udagram-frontend:local
      - run: docker push aklile/udagram-reverseproxy
      - run: docker push aklile/udagram-api-feed
      - run: docker push aklile/udagram-api-user
      - run: docker push aklile/udagram-frontend
