name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-api-feed:v4a aklile/udagram-api-feed:v4a
    - run: docker tag reverseproxy:v4a aklile/reverseproxy:v4a
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push aklile/udagram-api-feed:v4a
    - run: docker push aklile/reverseproxy:v4a