name: Node.js CI

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

  steps:

    - name: Git Checkout
        uses: actions/checkout@v2
    - name: Build Docker Image
        run: docker-compose -f docker-compose-build.yaml build --parallel
    - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - name: Push Image to Docker Hub
        run: docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$GITHUB_RUN_NUMBER
        run: docker push aklile/udagram-reverseproxy:v3a
        run: docker push aklile/udagram-api-feed:v4a
        run: docker push aklile/udagram-api-user:v4a
        run: docker push aklile/udagram-frontend:local
